# Ansible inventory created from ['/workspaces/DevOps-2023/netlab/topology.yml', 'package:topology-defaults.yml']
#

ansible_connection: docker
ansible_network_os: frr
ansible_python_interpreter: auto_silent
ansible_user: root
netlab_initial: always
netlab_mgmt_vrf: true
netlab_show_command:
- vtysh
- -c
- show $@
